### ISSUE TITLE
After running download, there's nothing in the DB

### ISSUE THREAD

**Issue by francislavoie** [NotJoeMartinez/yt-fts#161] opened 2024-07-21 05:53 UTC
This is what I tried:

```
$ yt-fts download --number-of-jobs 5 "https://www.youtube.com/channel/UCaxar6TBM-94_ezoS00fLkA"
```

This channel has something like 8.8k videos (quite a lot) so it took a good half hour to run. After running it, I run `yt-fts list` and no new channel is added.

As a sanity check, I then tried it against my own personal youtube channel (which has like, 20 videos, 3 of which had generated subs) and it worked fine and added the subtitles to the DB.

So something must be weird about this channel. As a sample of the log output:

I get tons of these, I figure this just means a video doesn't have subtitles:

```
WARNING: [youtube] vsJVEOLjRcM: nsig extraction failed: You may experience throttling for some formats
         n = mEPEUHKmGeMrduZp ; player = https://www.youtube.com/s/player/d60b0ef9/player_ias.vflset/en_US/base.js
```

I also get some of these (much less common):

```
ERROR: Did not get any data blocks
ERROR: Unable to download video subtitles for 'en': ERROR: Did not get any data blocks
```

And of course I get tons of these which I'm pretty sure are successful downloads:

```
[download] 100% of  112.96KiB in 00:00:00 at 1.27MiB/s -> NbuMCyvPJA8.en.vtt
```

But at the end, it just ended on a download, with no other output. I tried running the download twice, just in case I somehow did something wrong the first time, but nope it still didn't save the output the second time either.

I went through the DB with `sqlite3 ~/.config/yt-fts/subtitles.db` and none of the tables had any data at all except the config table with a couple default rows I guess. But channels and subtitles were empty.

All that said, I ended up using https://videomentions.com/search to find what I was looking for in a channel. But it would still be neat to get it working so I could do local searches in the future on this channel.

**Comment by NotJoeMartinez** [comment] 2024-07-21 18:05
@francislavoie thanks for reporting this. Do you mind sharing the version you are on? you can find that by running `yt-fts --version`. I made recent changes to how the subtitles are parsed and that might be the culprit. Thanks.

**Comment by francislavoie** [comment] 2024-07-21 18:36
I just installed it yesterday with pip so I assume the latest. Afk at the moment but will circle back ASAP

**Comment by francislavoie** [comment] 2024-07-21 23:35
```
$ yt-fts --version                                                                   
yt_fts version: 0.1.54
```

**Comment by alexmolas** [comment] 2024-07-22 09:41
I'm having the same issue. I tried the README example with @3blue1brown and it worked, but then I tried with @godago and the captions weren't added to the database. I got some warnings like


```
WARNING: [youtube] uPjO5o6vgE8: nsig extraction failed: You may experience throttling for some formats
         Install PhantomJS to workaround the issue. Please download it from https://phantomjs.org/download.html
         n = AeShK02qVZmCyONL ; player = https://www.youtube.com/s/player/d60b0ef9/player_ias.vflset/en_US/base.js
```

and some python errors like

```
ERROR: Did not get any data blocks
ERROR: Unable to download video subtitles for 'en': ERROR: Did not get any data blocks
Traceback (most recent call last):
  File "path/to/site-packages/yt_dlp/YoutubeDL.py", line 4331, in _write_subtitles
    self.dl(sub_filename, sub_copy, subtitle=True)
  File "path/to/site-packages/yt_dlp/YoutubeDL.py", line 3180, in dl
    return fd.download(name, new_info, subtitle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/site-packages/yt_dlp/downloader/common.py", line 466, in download
    ret = self.real_download(filename, info_dict)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/site-packages/yt_dlp/downloader/http.py", line 370, in real_download
    return download()
           ^^^^^^^^^^
  File "path/to/site-packages/yt_dlp/downloader/http.py", line 336, in download
    self.report_error('Did not get any data blocks')
  File "path/to/site-packages/yt_dlp/YoutubeDL.py", line 1073, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "path/to/site-packages/yt_dlp/YoutubeDL.py", line 1012, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: Did not get any data blocks

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "path/to/venv/bin/yt-fts", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "path/to/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "path/to/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/site-packages/yt_fts/yt_fts.py", line 88, in download
    dl_status = download_channel(channel_id, channel_name, language, number_of_jobs, s)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/site-packages/yt_fts/download.py", line 272, in download_channel
    download_vtts(number_of_jobs, list_of_videos_urls, language, tmp_dir)
  File "path/to/site-packages/yt_fts/download.py", line 146, in download_vtts
    futures[i].result()
  File "path/to/lib/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "path/to/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "path/to/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/site-packages/yt_fts/download.py", line 168, in get_vtt
    ydl.download([video_url])
  File "path/to/site-packages/yt_dlp/YoutubeDL.py", line 3583, in download
    self.__download_wrapper(self.extract_info)(
  File "path/to/site-packages/yt_dlp/YoutubeDL.py", line 3558, in wrapper
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "path/to/site-packages/yt_dlp/YoutubeDL.py", line 1595, in extract_info
    return self.__extract_info(url, self.get_info_extractor(key), download, extra_info, process)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/site-packages/yt_dlp/YoutubeDL.py", line 1606, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/site-packages/yt_dlp/YoutubeDL.py", line 1762, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/site-packages/yt_dlp/YoutubeDL.py", line 1821, in process_ie_result
    ie_result = self.process_video_result(ie_result, download=download)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/site-packages/yt_dlp/YoutubeDL.py", line 2993, in process_video_result
    self.process_info(new_info)
  File "path/to/site-packages/yt_dlp/YoutubeDL.py", line 3247, in process_info
    sub_files = self._write_subtitles(info_dict, temp_filename)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/site-packages/yt_dlp/YoutubeDL.py", line 4338, in _write_subtitles
    self.report_error(msg)
  File "path/to/site-packages/yt_dlp/YoutubeDL.py", line 1073, in report_error
    self.trouble(f'{self._format_err("ERROR:", self.Styles.ERROR)} {message}', *args, **kwargs)
  File "path/to/site-packages/yt_dlp/YoutubeDL.py", line 1012, in trouble
    raise DownloadError(message, exc_info)
yt_dlp.utils.DownloadError: ERROR: Unable to download video subtitles for 'en': ERROR: Did not get any data blocks
```

apparently, `yt_dlp` is not finding subtitles in English for some of the videos.

**Comment by NotJoeMartinez** [comment] 2024-07-22 19:23
The `nsig extraction failed` error was caused by [this](https://github.com/yt-dlp/yt-dlp/issues/10391) bug in the yt-dlp package, fixed by bumping the yt-dlp version to `2024.7.16`. This is not what causes the program to skip vtt parsing although fixing it results in much more successful transcript downloads. 

The problem is with the `ERROR: Did not get any data blocks` traceback from [get_vtt](https://github.com/NotJoeMartinez/yt-fts/blob/85aa66e9dc3e189a0f9d278ed9b5c10bba448794/yt_fts/download.py#L155) which occurs unpredictably. This might be caused by a new rate-limiting method from YouTube as I was only able to trigger it after re-downloading the `@godago` channel a couple of times from the same IP. For some reason (probably related to multithreading) the program will continue to download the channel transcripts after this error occurs but then fail to insert the transcripts into the database. 

I added a hotfix by wrapping the call to `ydl.download([video_url])` in a `try/except`. 
```python

def get_vtt(tmp_dir, video_url, language):  # download

    try: 
        ydl_opts = {
            'outtmpl': f'{tmp_dir}/%(id)s',
            'writeinfojson': True,
            'writeautomaticsub': True,
            'subtitlesformat': 'vtt',
            'skip_download': True,
            'subtitleslangs': [language, '-live_chat'],
            'quiet': True,
            'progress_hooks': [quiet_progress_hook]
        }

        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            ydl.download([video_url])

    except Exception as e:
        console.print(f"Failed to get: {video_url}\n{e}")
```

Ideally, we want a retry method or to avoid the rate limit altogether which could be possible with user agent randomization.

**Comment by NotJoeMartinez** [comment] 2024-07-22 19:55
This should be resolved in [v0.1.55](https://github.com/NotJoeMartinez/yt-fts/releases/tag/v0.1.55).  I did not test on the given channel but did test on https://www.youtube.com/@GothamChess which has ~2k videos. Feel free to ping me if you still experience the error and I will reopen the issue. Thanks again for reporting this.

**Closed by NotJoeMartinez** 2024-07-22 19:55 UTC

**Comment by francislavoie** [comment] 2024-07-22 20:03
Thanks, running it now :hourglass:

**Comment by francislavoie** [comment] 2024-07-22 20:26
```

**Comment by francislavoie** [comment] 2024-07-22 23:28
I'm seeing stuff like this occasionally
```
ERROR: Did not get any data blocks
ERROR: Unable to download video subtitles for 'en': ERROR: Did not get any data blocks
[download]   15.00KiB at  151.07KiB/s (00:00:00)Failed to get: https://www.youtube.com/watch?v=zk96P3uTTdw
[1m[0;31mERROR:[1m[0m Unable to download video subtitles for 'en': [1m[0;31mERROR:[1m[0m Did not get any data blocks

WARNING: [youtube] Webpage contains broken formats (poToken experiment detected). Ignoring initial player response
WARNING: [youtube] API returned broken formats (poToken experiment detected). Retrying (1/3)...
```

It seems to run slower overall, maybe because of the retries? I suppose that would be expected.

Took about 2-2.5 hours to finish. That might be as expected :man_shrugging: but it did save properly this time!

**Comment by NotJoeMartinez** [comment] 2024-07-23 01:19
A slower download would be expected because I think `yt-dlp` skips the video when `nsig extraction failed` is printed. The `ERROR: Did not get any data blocks` seems to be caused by rate limiting but it doesn't mean the video doesn't have a transcript. You can use the `update` command to add any videos missed by the first attempt 
```
yt-fts update --number-of-jobs 8 --channel 1
```
